### ISSUE TITLE
[1.16.3] Client crash If the mod is on the client but not on the server.

### ISSUE THREAD

**Issue by ProsperCraft** [henkelmax/reap#1]
**Bug description**
I right clicked to sleep on a bed and crashed.

**Steps to reproduce the issue**
Log in to a multiplayer server, right click on a bed.
Instacrash.

**Log files**
Crash report
https://gist.github.com/ProsperCraft/6aa97635ebaa2027f7d403834d400686
Logs
[latest.log](https://github.com/henkelmax/reap/files/5318365/latest.log)
Reproduced here -
https://gist.github.com/ProsperCraft/16565c4d4740666db10998858294e255

**Versions**
- Minecraft version  1.16.3
- Forge version 34.1.1
- Mod version reap-1.16.3-1.0.1

**Other mods**
https://www.curseforge.com/minecraft/modpacks/towncraft

**Comment by ProsperCraft** [comment]
Update- tested in single player and it doesn't crash, only when on a dedicated server.

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
Unfortunately I am not able to reproduce this issue. Can you try if it crashes without other mods installed?
If it doesn't crash without mods, can you narrow down the mod that causes this behavior?

**Comment by ProsperCraft** [comment]
I found that it was due to having it on the client but not on the server,  so an unhandled exception I guess.

**Comment by henkelmax** [comment]
You should always have this mod installed on both sides!
