### ISSUE TITLE
continuation of Project MMO Support

### ISSUE THREAD

**Issue by andr9528** [henkelmax/reap#10]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/reap/faq)!**

Could you take a lookt at the message from one of the Porject MMO people on the issue from the other day?

Issue: https://github.com/henkelmax/reap/issues/9

**Comment by henkelmax** [comment]
I already said everything that needs to be said. As it might fix compatibility with this mod, it might break a lot of other mods.
