### ISSUE TITLE
Harvested crops appears to multiply seeds

### ISSUE THREAD

**Issue by Raidobw2** [henkelmax/reap#12]
**Bug description**
Harvesting a crop appears to be duplicating the seed. For example if a crop is supposed to drop 1 seed, it will now drop two. This makes it abusable by just filling your inventory with bone meal and spamming on crops, since you always get an extra seed.

Thank you in advance for looking into it. More information below:

**Steps to reproduce the issue**
By inspecting Minecraft loot tables and checking the wiki https://minecraft.fandom.com/wiki/Wheat_Seeds we can confirm wheat seeds can only drop 3 seeds at most when harvested with an empty hand. This has roughly a 18% chance of happening.

1. Harvest a fully grown wheat crop with right click with Reap
2. You have 18% chance of getting 4 seeds, repeat if needed and use bone meal
3. You get 4 seeds
4. The crop is not broken and you have 4 seeds. In total, there are now 5 seeds for that operation
5. The seed is now duplicated

This is even more easily demonstrated with Mystical agriculture, since the mod is known to prevent secondary seed drops (seeds are crafted and hard to make). But then you can duplicate the seeds from their mod with Reap.

**Expected behavior**
The seed should not be multiplied. An example of this fix being implemented is from Create at https://github.com/Creators-of-Create/Create/blob/3d5af741aff8c6535835f488db318b4b0e9bc1ec/src/main/java/com/simibubi/create/content/contraptions/components/actors/HarvesterMovementBehaviour.java#L101. They substract the seed, preventing multiplication of the item.

**Versions**
- Minecraft version: `1.18.2`
- Forge version: `40.1.0`
- Mod version: `reap-1.18.2-1.0.0.jar`

**Other mods**
You can replicate with only vanilla and Reap following my previous instructions.

**Screenshots (Optional)**
I've tested this with Minecraft, Mystical Agriculture and Floralis to give you a better understanding of the issue:

https://user-images.githubusercontent.com/17010632/166641866-defa0242-f07c-4384-b8a5-ea4525174982.mp4

Here is another example of this in action:

https://user-images.githubusercontent.com/17010632/166642795-789d2002-27bb-4d55-b320-fb415fb11c93.mp4

**Comment by henkelmax** [comment]
This mechanic is completely intended.
Since the mod only drops the contents of the loot table of the block. It is not aware of the type of item that is used to plant the crop. There is also no programmatic way of reliably finding out which seed corresponds to which block, since seeds can have different items to plant them.
I would generally not recommend this mod for crops that rely on not having duplicate seeds like mystical agriculture etc.
