### ISSUE TITLE
config wildcard usage

### ISSUE THREAD

**Issue by Warbringer12** [henkelmax/reap#13]
**Is your feature request related to a problem? Please describe.**
would like to have it where I can use wildcard inside of the config so I don't have to go through every individual crop for certain mods and put them into the list

**Describe the solution you'd like**
the use of wildcard inside of config

**Describe alternatives you've considered**
none

**Additional context**
tried using wildcard inside config just breaks when loading in

**Comment by henkelmax** [comment]
How would that wildcard work?

**Comment by Warbringer12** [comment]
it would allow people the ability to basically put something like this minecraft:* instead of having to put each block id into the config

**Comment by henkelmax** [comment]
That won't work. it would cause weird behavior with blocks that aren't crops.

**Comment by henkelmax** [comment]
Closed due to inactivity
