### ISSUE TITLE
Modded Harvestability Config

### ISSUE THREAD

**Issue by KuwuroUsagi** [henkelmax/reap#14]
I'd like to add right click  harvestability to modded crops, but it seems as though I may not be able to use the "umbrella" tags, do I have to name each individual item for whitelisting?
My current config that doesnt seem to be working for Harvestcraft2, Mystical Agriculture, or Vanilla crops (sugar cane, wheat, carrots, cocoa beans, etc)
> [crop_harvesting]
> 	#The blocks that should get harvested by right-clicking
> 	whitelist = ["minecraft:crops", "mysticalagriculture:crops", "forge:crops"]
> 	#If the held tool should be considered when right-click harvesting
> 	consider_tool = true

I've tried holding a hoe, using an open hand, crouching and not crouching etc.

If I had to assume, I'd think that just using minecraft:crops as a whitelist *should* whitelist every correctly implemented mod crop as it's a common tag they use, but it seems it doesn't work very well.

**Comment by henkelmax** [comment]
Tags need to start with a `#`
