### ISSUE TITLE
Mystical Agriculture Seed drops every time

### ISSUE THREAD

**Issue by RoyalReject** [henkelmax/reap#16]
**Please read the [FAQ](https://modrepo.de/minecraft/reap/faq) before submitting a bug report!**

**Bug description**
When adding the tag for mystical agriculture seeds to be an effected crop and you harvest it it drops a seed every time, this should only happen occasionally has it has a config for secondary seeds drops or not that is a random chance not every time, this also effects 
Mystical Agradditions and tier 6 seeds that should not drop at all

**Steps to reproduce the issue**
1. Have reap mod and mystical agriculture mod installed
2. Add "#mysticalagriculture:crops" to whitelist
3. Either apply fertilizer or wait for crop to grow
4. right click harvest crop

**Expected behavior**
It should not drop a seed on every harvest

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.19.2
- Forge version: 43.1.47
- Mod version: 1.19.2-1.0.0

**Notes**
I have tested a few other mods that have similar functions and https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease does not have this issues but I would rather use the reap mod as I also enjoy the tree function

**Comment by CrossVas** [comment]
https://github.com/henkelmax/reap/blob/6a55df97b7f1aacba9d9554de61ffcca1a94c221/src/main/java/de/maxhenkel/reap/CropEvents.java#L80-L82

This needs to check if stack item is instance of seed/plantable of clicked block. If so, shrink it before drop. 

```java
            ItemStack plantable = clickedBlock.getCloneItemStack(level, pos, state);
            for (ItemStack stack : drops) {
                if (stack.is(plantable.getItem())) {
                    stack.shrink(1);
                }
                Containers.dropItemStack(level, pos.getX(), pos.getY(), pos.getZ(), stack);
            }
```
