### ISSUE TITLE
Right click the portable square to harvest crops, causing the portable square to disappear

### ISSUE THREAD

**Issue by flycran** [henkelmax/reap#17]
**Bug description**
Right click the portable square to harvest crops, causing the portable square to disappear.
The box that disappears after restarting the world will be restored to the item list.

**Steps to reproduce the issue**
It's very clear

**Expected behavior**
It should not consume handheld squares

**Log files**
null

**Versions**
- Minecraft version 1.18.2
- Forge version 40.1.92
- Mod version 1.0.0

**Other mods**
[[1.18.2]LC:Wilds1.2Beta2](https://www.curseforge.com/minecraft/modpacks/lcw/files/4264425)

**Comment by henkelmax** [comment]
What do you mean with portable square?

**Comment by henkelmax** [comment]
Closed due to inactivity

**Comment by flycran** [comment]
I don't understand English, so put the original text here

### 错误描述
手持方块右键单击作物以收获，导致手持方块消失。
重启世界后消失的方块将恢复到物品列表中。
