### ISSUE TITLE
This is just a 1.20 request

### ISSUE THREAD

**Issue by Duxtorm** [henkelmax/reap#19]
There've been a lot of issue with mods being updated to either _only 1.20_ or _only 1.20.1_ which means making a mod pack for either version requires a lot of pick & choosing and sacralises..
If it's not too much of a hassle, I'd be very appreciative of a 1.20 release.

**Comment by henkelmax** [comment]
Sorry, but I will only support the latest release of a Minecraft version. 1.20 was only 5 days old since 1.20.1 released. Forge also stopped developing that version, so its unstable and not worth supporting at all.
Also most 1.20 mods are compatible with 1.20.1

**Comment by Duxtorm** [comment]
Yeah, that's okay, just thought I'd ask.
Through testing, I've found the majority of 1.20.1 mods aren't compatible with 1.20, especially the ones that add items- (and this one)
