### ISSUE TITLE
Clicking on a Crafting Table Crashes the Game

### ISSUE THREAD

**Issue by ultranine** [henkelmax/reap#2]
**Please read the [FAQ](https://modrepo.de/minecraft/reap/faq) before submitting a bug report!**

**Bug description**
Upon entering a world and clicking a crafting table, the game freezes before showing a "Saving World..." screen and crashing.

**Steps to reproduce the issue**
1. Go to any crafting table.
2. Click on the crafting table.

**Expected behavior**
The crafting table opening.

**Log files**
Crash Log: https://gist.github.com/ultranine/d8363c55596e7954a25b4baa288d7d16
Game Log: https://gist.github.com/ultranine/9abe5f9ec91ff923efeebca8ff7d49d4

**Versions**
- Minecraft Version: 1.16.4
- Forge version: 35.0.2
- Mod version: 1.16.4-1.0.0

**Other mods**
-Large Ore Deposits
-Aquaculture 2
-BackTools
-Biomes O' Plenty
-Cloth Config API
-CraftTweaker
-Ding!
-FastLeafDecay
-Forge Endertech
-iChunUtil
-IKWID
-JEI
-JEITweaker
-Light Level Overlay
-Pam's HarvestCraft 2: Core
-Pam's HarvestCraft 2: Crops
-PFM
-Shutup, Experimental Settings!
-Spice of Life: Carrot Edition
-StartupQOL
-Survivalist
-Survive
-Total Darkness
-UnionLib

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Thanks for reporting this issue. It should be fixed in the next version.
