### ISSUE TITLE
When I play SkyBlock on hypixel, my MC will crash as soon as I click on the workbench.

### ISSUE THREAD

**Issue by su2u4-1** [henkelmax/reap#22]
### Bug description

[crash-2024-03-02_20.39.09-client.txt](https://github.com/henkelmax/reap/files/14469373/crash-2024-03-02_20.39.09-client.txt)
This is the crash report
When I was playing SkyBlock on Hypixel and opened the crafting table, my Minecraft crashed.
I'm not using the official launcher; I'm using MultiMC.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.2

### Mod loader and version

forge 47.2.0

### Steps to reproduce

1. Open MC and play hypixel
2. Go play SkyBlock
3. Click on the workbench
4. Crash!!!

### Log files

https://gist.github.com/su2u4-1/5a5251c48d82768bcf7f9bb66e4491b7

**Comment by henkelmax** [comment]
This mod is **required** on both server and client.
