### ISSUE TITLE
Reap 1.16.4-1.0.2 + Biomes O Plenty, Breaking trees only breaks bottom two blocks

### ISSUE THREAD

**Issue by DialgoPrima** [henkelmax/reap#3]
**Please read the [FAQ](https://modrepo.de/minecraft/reap/faq) before submitting a bug report!**

**Bug description**
I added in the different wood types from the Biomes O Plenty mod into the reap-server.toml file, but now all trees, including vanilla trees, will only break the bottom two logs when using any level axe on the bottom block.

**Steps to reproduce the issue**
1. Create New World
2. Save World and replace reap-server.TOML in the serverconfig folder with the modified TOML that includes the BoP logs
3. Reload World
4. Trees only break the bottom two blocks when mined with any axe

**Expected behavior**
The entire tree would break when mined with an axe at the bottom block.

**Log files**
Please provide log files of the game session in which the problem occurred.
[Latest Log](https://gist.github.com/DialgoPrima/1ae26dd6fc5ac349130d11e0768b1aeb)
[The text contained in my modified TOML file](https://gist.github.com/DialgoPrima/b9e605041d142e999f43dbaae3fa1532)

**Versions**
- Minecraft version 1.16.4
- Forge version 1.16.4-forge-35.1.36
- Mod version 1,16,4-1.0.2

**Other mods**
AmbientSounds_v3.1.4_mc1.16.4
BiomesOPlenty-1.16.4-13.0.0.428-universal
CreativeCore_v2.0.10_mc1.16.4
embellishcraft-1.16.4-3.3.0.0
embellishcraft-bop-1.16.4-3.3.0
FastLeafDecay-v25
jei-1.16.4-7.6.1.65
mapperbase-1.16.4-2.3.0.0
preview_OptiFine_1.16.4_HD_U_G6_pre12

The problem does still occur when Reap is the only mod installed.

**Screenshots (Optional)**
[I have a short video showing the bug in it's entirety.](https://youtu.be/KHcikr4VmBU)

**Comment by henkelmax** [comment]
The problem is that you somehow included a block that doesn't exist in the log config. If this is the case, Minecraft will automatically torn it into an air block. This means you are "harvesting" the air around the tree. I will create an exception for air, so this won't happen when adding a block to the config.

**Comment by DialgoPrima** [comment]
I double checked, and I guess the Ethereal trees were previously removed, so the block no longer existed, as you guessed. I removed it from the config and it fixed the trees not fully breaking. Thank you for your help!

**Comment by henkelmax** [comment]
No problem!

The next version should work regardless of missing blocks.
