### ISSUE TITLE
Config Files

### ISSUE THREAD

**Issue by SuperVenti** [henkelmax/reap#8]
I don't know if it's a bug or it should be like this, but the mod does not create other config files, only the "server-config" and i dont know if there are any possibilities to set a server-config as default for every world generation. What can i do whit this situation?

**Comment by henkelmax** [comment]
The server config is the only config there is in this mod.
Take a look at the forge config documentation on how to create default configs.

**Comment by BigAl607** [comment]
So there's no client config? I'm using 1.21.1-1.1.2, and I want to change it so that reap is active when holding crouch, and not when standing normal
