### ISSUE TITLE
Project MMO Support

### ISSUE THREAD

**Issue by andr9528** [henkelmax/reap#9]
**Bug description**
Right clicking a crop to harvest it with the use of this mod, does not yield farming experience in Project MMO.

From my bug report to them (on their discord server), they say that the correct Forge events are not being fired on harvest by my right-click harvest mod ie. this mod.

**Steps to reproduce the issue**
1. Install Project MMO
2. Install Reap
3. Load up a world
4. Right-click a harvestable crop
5. Notice that no experience in farming is gained.

**Expected behavior**
I'd expect to gain experience farming whether i break and replace or right click the crop to harvest it.

**Log files**
No logs for this problem.

**Versions**
- Minecraft version: 1.18
- Forge version: 38.0.14
- Mod version: reap-1.18-1.0.1

**Other mods**
- Project MMO version Project_MMO-1.18-3.65.1

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Did you add the crops to the config?

**Comment by andr9528** [comment]
Which config are you refering to? Project MMO or Reap?
I am gaining experience for breaking the crops normally.

Also the ModRepo for this mod links to the wrong issue page when you click 'Issues' just fyi.

**Comment by henkelmax** [comment]
> Which config are you refering to? Project MMO or Reap?

Every non vanilla crop needs to be added to the reap config.

> I am gaining experience for breaking the crops normally.

This is not a feature of this mod.

> Also the ModRepo for this mod links to the wrong issue page when you click 'Issues' just fyi.

Alright, thanks, I will look into that

**Comment by andr9528** [comment]
Reap does what it should - allowing right click to harvest crops... However it doesn't fire the necessary forge events for other mods to register that a crop was harvested. As such Project MMO does not award the farming experience that is normally gained when breaking/replacing a crop.

My config, for Reap, for the world where i noticed this is below
![image](https://user-images.githubusercontent.com/21788044/145094933-900d1775-0c54-4478-94c1-120b7805c53a.png)

EDIT: I was just harvesting Wheat

**Comment by henkelmax** [comment]
Firing the right events would be breaking more than it would help, since some crops have different seeds than crops. I'm sorry, but that's a wontfix.

**Comment by Caltinor** [comment]
Posting this event should have no impact on your mod. That might only be the case if you wanted the event to be cancellable, in which case you would want to check the event result prior to executing your code. Adding this at any point during your reap logic will suffice. `MinecraftForge.EVENT_BUS.post(new BreakEvent(...));`
*(I left out the event parameters for brevity)*
